site_name: JustRaincoat/Notebook
site_description: OI 算法笔记
site_url: https://oi.notebook.justraincoat.top
repo_url: https://github.com/JustRaincoat/Notebook
repo_name: JustRaincoat/Notebook
edit_uri: ""

docs_dir: docs

site_dir: /var/www/anki.justraincoat.top

exclude_docs: |
  /.git/
  /.vscode/
  /.crossnote/
  /icon/
  /Code/
  /notebook.json
  /LICENSE
  /README.md
  /README.html
  /*.html
  /**/*.html
  /mkdocs.yml

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换亮色模式
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 切换暗色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - announce.dismiss
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax-config.js
  - assets/mathjax/tex-mml-chtml.js
  - assets/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
